package spring.jpa.eclipselink.utils;

/**
 * The Enum ConfigEnum.
 */
public enum ConfigEnum {

	QTD_MAX_FALHAS_PARA_RESET,

	TEMPO_BLOQUEIO,

	QTD_DIGITOS_SENHA,

	PERIODO_EXPIRACAO_SENHA,

	QTD_DIGITOS_REPETIDOS_SENHA,

	QTD_MAX_PERMITIDO_PARA_RESET,

	QTD_DIGITOS_CODIGO_AUTORIZACAO,

	VALIDADE_CODIGO_AUTORIZACAO,

	SEPARADOR,

	QTD_MAX_TENTATIVAS_INVALIDAS_AUTORIZACAO,

	QTD_MAX_DIGITOS_CODIGO_AUTORIZACAO,

	VALIDADE_CODIGO_AUTORIZACAO_ANO,

	PERIODO_MINUTOS_EXPIRACAO_SENHA,

	REGENCIA_VALIDACAO_EMAIL,

	REGENCIA_VALIDACAO_ALFA_MAIUSCULO,

	REGENCIA_VALIDACAO_ALFA_MINUSCULO,

	REGENCIA_VALIDACAO_NUMERO,

	REGENCIA_VALIDACAO_CARACTER_ESPECIAL,

	CONJUNTO_CARACTERES_ALFA_MAIUSCULO,

	CONJUNTO_CARACTERES_ALFA_MINUSCULO,

	CONJUNTO_NUMEROS,

	CONJUNTO_CARACTERES_ESPECIAIS
}
